services:
  - type: web
    name: quiz-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.4
